version: 2

sources:
  - name: deel_globepay
    description: "Source data from Globepay."
    database: DEEL_GLOBEPAY
    schema: RAW
    tables:
      - name: acceptance
        description: "Raw data from Globepay acceptance transactions."
      - name: chargeback
        description: "Raw data from Globepay chargeback report."